In [2]:
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.preprocessing import Imputer
from sklearn.model_selection import cross_val_score

DATA = 'dataset/loan_one_hot_encoded.csv'

In [3]:
df = pd.read_csv(DATA)
Y = df['loan_created']
X = df.drop('loan_created', axis=1)

Things to-do:

- [ ] The data is missing values; use Imputer to fill mean/median of the column
    - [ ] Create another column to denote whether the data was imputed or not; I've read that it seems to have better results
- [ ] Set class_weights in SVM
- [ ] Tune hyperparameters
- [ ] Specific kernel? 

What to do about skewed data:
- See as an anamoly detection problem?
- class weights (for SVM)
- Remove training data (less data anyway..:( )


In [4]:
imp = Imputer()
imputed_X = imp.fit_transform(X)

In [5]:
imputed_X.shape

(230, 242)

In [6]:
reverse_Y = Y.apply(lambda x: 0 if x == 1 else 1)

In [16]:
k_fold = 6
clf_params = {
    'class_weight': 'balanced',
#     'kernel': 'linear',
    'C': 10,
#     'degree': 3, 
#     'gamma': 'auto',
}

clf1 = SVC(kernel='poly', class_weight='balanced')
clf2 = SVC(kernel='poly', class_weight='balanced')

scores1 = cross_val_score(clf1, imputed_X, Y, cv=k_fold)
scores2 = cross_val_score(clf2, imputed_X, reverse_Y, cv=k_fold)
print(scores1)
print(scores2)

[ 0.92307692  0.8974359   0.8974359   0.84210526  0.92105263  0.89189189]
[ 0.92307692  0.8974359   0.8974359   0.84210526  0.92105263  0.89189189]


In [14]:
# n_samples / (n_classes * np.bincount(y))
X.shape[0] / (2*np.bincount(Y))

array([  0.52036199,  12.77777778])